### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by userkilled** [metabrainz/listenbrainz-android#104]
Hello, how to translate the application, because I almost translated Strings, but here I am collecting the project. Not everything is clear where to take a normal supply of words for translation?

**Comment by 07jasjeet** [comment]
Not sure what you're saying there. Can you describe the issue more briefly?

**Comment by akshaaatt** [comment]
We have plans to use weblate for the translations @userkilled, but not for now. We will take it up once the app becomes significant.

Thanks for your concerns :) Please report such issues as a ticket on our forum.
