### ISSUE TITLE
ViewPager does not changing its pages in BrainzPlayerBackDropScreen. 

### ISSUE THREAD

**Issue by SB2318** [metabrainz/listenbrainz-android#118]
This is a **TODO** task. I want to work on this. Please assign it to me.

Here is the demo Video:

https://user-images.githubusercontent.com/87614560/228625725-7d23d01a-4c8e-4969-84f0-5786059b2655.mp4

**Comment by akshaaatt** [comment]
@SB2318 please create a ticket on jira and take it up there. Thanks!

**Comment by SB2318** [comment]
Okay 😇
