### ISSUE TITLE
Apps crashes at start

### ISSUE THREAD

**Issue by retiolus** [metabrainz/listenbrainz-android#146]

**Comment by 07jasjeet** [comment]
Thanks for reporting! Release 1.4.1 is out with the fix. Feel free to report any crashes you face [here](https://tickets.metabrainz.org/secure/RapidBoard.jspa?rapidView=10&projectKey=MOBILE) if possible.

**Comment by regorxxx** [comment]
Where is the 1.4.1 in github? I see no 1.4.1 apk available (not using google services).

**Comment by 07jasjeet** [comment]
> Where is the 1.4.1 in github? I see no 1.4.1 apk available (not using google services).
> 
> 
> 
> I can confirm crashes on fiio m11 with 1.4.0 at startup too.

Play store shows 1.4.1 on my device. Can you please check again? I do agree that github isn't showing the 1.4.1 update but our commit history has it.

If you still can't see 1.4.1 update after dedicatedly searching for the app on play store, please let us know.

**Comment by regorxxx** [comment]
Maybe I didn't explain it right, I don't use google play, so I was in fact asking for the apk within github (wich is missing the 1.4.1 tag and release).

**Comment by 07jasjeet** [comment]
> Maybe I didn't explain it right, I don't use google play, so I was in fact asking for the apk within github (which is missing the 1.4.1 tag and release).

Oh. No problems then, we'll make it available shortly.
