### ISSUE TITLE
Distribution through fdroid app store

### ISSUE THREAD

**Issue by tfranken90** [metabrainz/listenbrainz-android#191]
I've submitted a request for packaging on the f-droid app store. 

https://gitlab.com/fdroid/rfp/-/issues/2460

**Comment by amCap1712** [comment]
We use a closed source library in the app and so the app in the current form is not compliant with F-droid AFAIU.

https://github.com/metabrainz/listenbrainz-android/blob/main/app/lib/spotify-app-remote-release-0.7.2.aar

A possible solution could be to create a flavor the app that doesn't use this library.

**Comment by tfranken90** [comment]
I see, I was wondering why it wasn't already on fdroid. I'll close this issue for now.

**Comment by aardbol** [comment]
Can't you provide it in your own f-droid repo instead? Would be nice to get updates automatically like that

**Comment by ildar** [comment]
@aardbol , try https://android.izzysoft.de/repo/info
