### ISSUE TITLE
Add VLC as an option in listening apps

### ISSUE THREAD

**Issue by bobajeff** [metabrainz/listenbrainz-android#284]
In the settings, `Listening Apps` only lists Spotify, org.mozilla.fenix and ListenBrainz. However, I use VLC on Android to listen to music.

**Comment by 07jasjeet** [comment]
The app will only show up if we VLC posts a media notification to status bar. If the app isn't picking that up, please confirm. P.S we are already revamping the submission service so it'll get better in next update.

**Comment by bobajeff** [comment]
Oh, just checked your right it does show up when I'm open the app.
