### ISSUE TITLE
github misses release v2.4.0

### ISSUE THREAD

**Issue by basings** [metabrainz/listenbrainz-android#286]
Play store is a version ahead of the github release

**Comment by 07jasjeet** [comment]
We'll make a stable release in the next version, so please wait and thank you for using the app!

**Comment by aereaux** [comment]
No rush, but do you know when the next release will be?  I've been getting listenbrainz from the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid/index/apk/org.listenbrainz.android), but it hasn't been updated as recently because it takes the releases from github.  Thanks!

**Comment by 07jasjeet** [comment]
@aereaux We'll make a github release shortly, Thanks for informing.

**Comment by akshaaatt** [comment]
@aereaux please use the v2.4.2 release
