### ISSUE TITLE
"Send listens" toggle doesn't work 

### ISSUE THREAD

**Issue by Discostu36** [metabrainz/listenbrainz-android#324]
I want to temporarily disable logging listens on my device but when I disable the "send listens" option, close settings and reopen them, the toggle is active again.

v2.4.2
Android 13
Fairphone 4

**Comment by 07jasjeet** [comment]
@Discostu36 Is this issue specific to some apps or all of them?

**Comment by Discostu36** [comment]
I don't mean a specific app. This toggle doesn't stay off when I turn it off.

![Screenshot_20240106-222829_1](https://github.com/metabrainz/listenbrainz-android/assets/30999326/c0c96d0e-38b7-483c-b718-9a2fbc606c27)

**Comment by 07jasjeet** [comment]
Fixed in version 2.5.3 (currently in beta).
