### ISSUE TITLE
don't automatically scrobble any player

### ISSUE THREAD

**Issue by mikelpr** [metabrainz/listenbrainz-android#331]
I've been having to clean up my listens because the android app automatically scrobbles from any new player and it had been spamming my listens with KDE connect's player notifications of my computer playing where it is already scrobbling and in a better way (not using the app's name as the artist)

But most eerily, I just noticed today when I went again to check what apps was it scrobbling from, **it was scrobbling "Phone calls" from the Phone app and Signal** (shown as its package name, org.thoughtcrime.securesms)

**Comment by 07jasjeet** [comment]
Hello @mikelpr! First of all, thanks for the feedback. Our current objective is to tackle this problem only and a fix may be out soon. Join our beta program to get the latest updates first!

**Comment by 07jasjeet** [comment]
In version 2.5.3 (currently in beta), a new option has been added in the settings called "Enable new players" which decides if any new player should be used to submit listens or not. Please disable the option to not scrobble any new player.

**Comment by 07jasjeet** [comment]
Closing issue as its resolved. Please comment again to re-open this discussion.
