### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Discostu36** [metabrainz/listenbrainz-android#349]
Since update to 2.5.3 the app is not recording listens anymore. I have only tested plays from com.ventismedia.android.mediamonkey so far.

Android 13
Fairphone 4

**Comment by Discostu36** [comment]
It worked later in the evening. No idea about the source of the problem.

<details>
<summary>log</summary>
````
Logger started at 24-01-2024-17:50:37
App Version: 1706115037425 
Device Application Id: org.listenbrainz.android 
Device Version Code: 47 
Device Version Name: 2.5.3 
Device Build Type: release 
Device: FP4 
Device SDK: 33 
Device Manufacturer: Fairphone 


24-01-2024-17:50:37 D/ListenBrainz: Onboarding status: true 
24-01-2024-17:50:38 D/ListenBrainz: Service already running with name: ComponentInfo{org.listenbrainz.android/org.listenbrainz.android.service.ListenSubmissionService} 
24-01-2024-17:50:38 D/ListenBrainz: Onboarding status: true 
24-01-2024-17:50:38 D/ListenBrainz: Initializing Listener Service 
24-01-2024-17:50:38 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
24-01-2024-17:50:38 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
24-01-2024-17:50:38 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
24-01-2024-17:50:38 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
24-01-2024-17:50:38 D/ListenBrainz: Timer Set 
24-01-2024-17:50:38 D/ListenBrainz: Timer started 
24-01-2024-17:50:39 D/ListenBrainz: App remote Connected! 
24-01-2024-17:50:39 D/ListenBrainz: Submission failed, not saving listen because metadata is faulty. 
24-01-2024-17:50:39 D/ListenBrainz: Timer Set 
24-01-2024-17:50:39 D/ListenBrainz: Timer started 
24-01-2024-17:50:39 D/ListenBrainz: Track is too short to submit 
24-01-2024-17:50:40 D/ListenBrainz: Track is too short to submit 
24-01-2024-17:50:45 D/ListenBrainz: Event: start 
24-01-2024-17:50:46 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:50:53 D/ListenBrainz: ### REGISTERED MediaController Callback for org.listenbrainz.android. 
24-01-2024-17:51:18 D/ListenBrainz: App remote Connected! 
24-01-2024-17:51:23 D/ListenBrainz: Spotify: Player state subscription cancelled. 
24-01-2024-17:51:27 D/ListenBrainz: Event: start 
24-01-2024-17:51:27 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:51:52 D/ListenBrainz: App remote Connected! 
24-01-2024-17:51:52 D/ListenBrainz: Event: start 
24-01-2024-17:51:52 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:51:55 D/ListenBrainz: ### REGISTERED MediaController Callback for org.listenbrainz.android. 
24-01-2024-17:51:55 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
24-01-2024-17:51:56 D/ListenBrainz: ### REGISTERED MediaController Callback for org.listenbrainz.android. 
24-01-2024-17:52:33 D/ListenBrainz: App remote Connected! 
24-01-2024-17:52:39 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:52:39 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:52:47 D/ListenBrainz: App remote Connected! 
24-01-2024-17:53:00 D/ListenBrainz: App remote Connected! 
24-01-2024-17:53:24 D/ListenBrainz: App remote Connected! 
24-01-2024-17:53:27 D/ListenBrainz: App remote Connected! 
24-01-2024-17:55:56 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:55:56 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:56:12 D/ListenBrainz: App remote Connected! 
24-01-2024-17:56:43 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:56:43 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:57:31 D/ListenBrainz: App remote Connected! 
24-01-2024-17:58:05 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:58:05 D/ListenBrainz: Listen socket connected. 
24-01-2024-17:58:19 D/ListenBrainz: Spotify: Player state subscription cancelled. 
24-01-2024-17:58:19 D/ListenBrainz: App remote Connected! 
24-01-2024-18:01:16 D/ListenBrainz: App remote Connected! 
24-01-2024-18:01:26 D/ListenBrainz: App remote Connected! 
24-01-2024-18:01:27 D/ListenBrainz: Event: start 
24-01-2024-18:01:27 D/ListenBrainz: Listen socket connected. 
24-01-2024-18:13:17 D/ListenBrainz: App remote Connected! 
24-01-2024-18:13:55 D/ListenBrainz: App remote Connected! 
24-01-2024-18:23:29 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android
````
</details>

**Comment by 07jasjeet** [comment]
Hello @Discostu36, Thanks for the report and logs! 
All seems okay from the logs. Make sure you are not submitted listen lesser than 30 seconds because we discard those listens. Also, we have identified a bug with songs lesser than 60 seconds are onto fixing it.

**Comment by Discostu36** [comment]
After working for some time it now again doesn't scrobble my listens. 

<details>
Logger started at 15-03-2024-09:09:06
App Version: 1710490146528 
Device Application Id: org.listenbrainz.android 
Device Version Code: 51 
Device Version Name: 2.6.1 
Device Build Type: release 
Device: FP4 
Device SDK: 33 
Device Manufacturer: Fairphone 


15-03-2024-09:09:06 D/ListenBrainz: Initializing Listener Service 
15-03-2024-09:09:06 D/ListenBrainz: Service already running 
15-03-2024-09:13:35 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:13:35 D/ListenBrainz: Timer Set 
15-03-2024-09:13:35 E/null: META 
15-03-2024-09:13:35 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:13:35 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:13:35 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:13:37 D/ListenBrainz: Timer Set 
15-03-2024-09:13:37 E/null: META 
15-03-2024-09:13:37 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:13:46 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:13:46 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:22:36 D/ListenBrainz: Timer Set 
15-03-2024-09:22:36 E/null: META 
15-03-2024-09:22:36 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:22:45 D/ListenBrainz: Timer Set 
15-03-2024-09:22:45 E/null: META 
15-03-2024-09:22:45 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:29:41 D/ListenBrainz: Timer Set 
15-03-2024-09:29:41 E/null: META 
15-03-2024-09:29:41 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:30:41 D/ListenBrainz: Timer Set 
15-03-2024-09:30:41 E/null: META 
15-03-2024-09:30:41 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:30:42 D/ListenBrainz: Timer Set 
15-03-2024-09:30:42 E/null: META 
15-03-2024-09:30:42 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:30:48 D/ListenBrainz: Timer Set 
15-03-2024-09:30:48 E/null: META 
15-03-2024-09:30:48 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Onboarding status: true 
15-03-2024-09:31:34 D/ListenBrainz: Init connection to spotify. 
15-03-2024-09:31:34 D/ListenBrainz: Onboarding status: true 
15-03-2024-09:31:34 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:31:34 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:31:34 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:31:34 D/ListenBrainz: ### REGISTERED MediaController callback for com.ventismedia.android.mediamonkey. 
15-03-2024-09:31:34 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
15-03-2024-09:31:34 D/ListenBrainz: Timer Set 
15-03-2024-09:31:34 E/null: META 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:34 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:31:35 D/ListenBrainz: Spotify is not Connected. 
15-03-2024-09:31:35 D/ListenBrainz: Listen socket connected. 
15-03-2024-09:34:08 D/ListenBrainz: Timer Set 
15-03-2024-09:34:08 E/null: META 
15-03-2024-09:34:08 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:34:09 D/ListenBrainz: Timer Set 
15-03-2024-09:34:09 E/null: META 
15-03-2024-09:34:09 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:37:52 D/ListenBrainz: Init connection to spotify. 
15-03-2024-09:38:03 D/ListenBrainz: Spotify is not Connected. 
15-03-2024-09:38:04 D/ListenBrainz: Listen socket connected. 
15-03-2024-09:38:35 D/ListenBrainz: Timer Set 
15-03-2024-09:38:35 E/null: META 
15-03-2024-09:38:35 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:38:40 D/ListenBrainz: Timer Set 
15-03-2024-09:38:40 E/null: META 
15-03-2024-09:38:40 D/ListenBrainz: Job with token: null completed. 
15-03-2024-09:39:53 D/ListenBrainz: Init connection to spotify. 
</details>

**Comment by MaxEtMoritz** [comment]
I, too can no longer get the app to submit any listen. Tried clearing cache, then clearing the complete app data.

After signing in again, at first the listening apps dialog was completely empty, but force-stopping the app fixed that (maybe the listen service was initialized too early before necessary permissions were granted)

But still, I could not get the app to submit listens. The last listen that got submitted was on March 01, 20 days ago.

[27-02-2024-16-57-27.txt](https://github.com/metabrainz/listenbrainz-android/files/14707061/27-02-2024-16-57-27.txt)
That log file contains the last successful submitted listens and the first ones where nothing happened anymore.

[21-03-2024-18-33-58.txt](https://github.com/metabrainz/listenbrainz-android/files/14707189/21-03-2024-18-33-58.txt)
That one was right after I reset the app data.

[21-03-2024-21-13-20.txt](https://github.com/metabrainz/listenbrainz-android/files/14707214/21-03-2024-21-13-20.txt)
That one was after force stopping to fix the listening apps list. The first song played was played full, the others were just button spamming to maybe get at least a now playing submitted...

**Comment by Discostu36** [comment]
Any progress on this? Still not scrobbling

<details>
<summary>Log</summary>

````
REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:29:19 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:29:19 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:29:19 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:29:19 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:29:19 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:29:27 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:29:27 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:29:27 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:29:27 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:29:33 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:29:33 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:29:33 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:29:33 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:29:33 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:29:33 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:29:33 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:29:33 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:29:36 D/ListenBrainz: Timer Set 
11-08-2024-11:29:36 E/null: META 
11-08-2024-11:29:36 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:30:11 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:30:11 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:30:11 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:30:11 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:34:31 D/ListenBrainz: Timer Set 
11-08-2024-11:34:31 E/null: META 
11-08-2024-11:34:31 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:36:56 D/ListenBrainz: Init connection to spotify. 
11-08-2024-11:37:16 D/ListenBrainz: Spotify: Player state subscription cancelled. 
11-08-2024-11:37:17 D/ListenBrainz: Timer Set 
11-08-2024-11:37:17 E/null: META 
11-08-2024-11:37:17 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:38:41 D/ListenBrainz: Init connection to spotify. 
11-08-2024-11:39:11 D/ListenBrainz: Timer Set 
11-08-2024-11:39:12 E/null: META 
11-08-2024-11:39:12 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:41:34 D/ListenBrainz: Timer Set 
11-08-2024-11:41:34 E/null: META 
11-08-2024-11:41:34 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:42:40 D/ListenBrainz: Init connection to spotify. 
11-08-2024-11:42:41 D/ListenBrainz: Spotify is not Connected. 
11-08-2024-11:42:41 D/ListenBrainz: Listen socket connected. 
11-08-2024-11:42:54 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:42:54 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:42:54 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:42:54 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:42:55 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:42:55 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:42:55 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:42:55 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:45:56 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:45:56 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:45:56 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:45:56 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:46:02 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:46:02 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:46:02 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:46:02 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:46:02 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:46:02 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:46:02 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:46:02 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:46:09 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:46:09 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:46:09 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:46:09 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:46:47 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:46:47 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:46:47 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:46:47 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:47:45 D/ListenBrainz: ### UNREGISTERED MediaController Callback for org.listenbrainz.android. 
11-08-2024-11:47:45 D/ListenBrainz: ### UNREGISTERED MediaController Callback for com.synology.DSaudio. 
11-08-2024-11:47:45 D/ListenBrainz: ### REGISTERED MediaController callback for com.synology.DSaudio. 
11-08-2024-11:47:45 D/ListenBrainz: ### REGISTERED MediaController callback for org.listenbrainz.android. 
11-08-2024-11:48:27 D/ListenBrainz: Timer Set 
11-08-2024-11:48:27 E/null: META 
11-08-2024-11:48:27 D/ListenBrainz: Job with token: null completed. 
11-08-2024-11:50:32 D/ListenBrainz: Init connection to spotify. 
11-08-2024-11:52:26 D/ListenBrainz: Init connection to spotify. 
````
</details>

**Comment by 07jasjeet** [comment]
@Discostu36 try out version 2.7.2, if the app does not listen to a music app, restart that music app (only required once after update).

**Comment by 07jasjeet** [comment]
@Discostu36 if the problem is fixed, should I close this issue?

**Comment by Discostu36** [comment]
Problem is fixed, app is scrobbling my listens now seamlessly.
