### ISSUE TITLE
Question on permissions and signing details

### ISSUE THREAD

**Issue by IzzySoft** [metabrainz/listenbrainz-android#367]
My [recently enhanced scanner](https://gitlab.com/IzzyOnDroid/repo/-/issues/475) just reported on yesterday's update of your app:

```
! repo/org.listenbrainz.android_49.apk declares flag(s): usesCleartextTraffic
! repo/org.listenbrainz.android_49.apk declares sensitive permission(s):
  android.permission.READ_PHONE_STATE android.permission.READ_MEDIA_AUDIO
  android.permission.READ_MEDIA_IMAGES android.permission.READ_EXTERNAL_STORAGE
! repo/org.listenbrainz.android_49.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what those permissions are needed/used for – and also which "cleartext connections" are used? As for the `DEPENDENCY_INFO_BLOCK`, that's pretty easy to heal:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by 07jasjeet** [comment]
So to clarify the warnings:

1. `android:usesCleartextTraffic` is used in our login process. We use web-views to login and retrieve access tokens.
2. So, these permission are used by BrainzPlayer to create a database of songs in user's device that they can listen to via BrainzPlayer.
3. We will add it in next update.

**Comment by IzzySoft** [comment]
Scanner yelled at me again with today's update, asking for

* `usesCleartextTraffic` (you wrote "retrieve access tokens" – which to me sounds like a security issue when happening via unencrypted settings)
* `android.permission.READ_PHONE_STATE` and `android.permission.READ_MEDIA_IMAGES` (which you didn't answer yet
* `DEPENDENCY_INFO_BLOCK` (which you wrote will be added "in next update" – that would have been this one, right? But I do not see it in your `build.gradle` yet)

Apologies for nagging – but those who use my repo expect me to take care, and I don't want to disappoint them :wink:

**Comment by IzzySoft** [comment]
Wonderful, thanks a lot!

**Comment by IzzySoft** [comment]
Just a small heads-up: scanner here still reports

```
! repo/org.listenbrainz.android_54.apk declares sensitive permission(s):
  android.permission.READ_MEDIA_IMAGES
```

Was that overlooked, or is it still coming? Or is it indeed needed and we should add a reason what for?

**Comment by 07jasjeet** [comment]
@IzzySoft this was added deliberately again. We need this permission for our Year in Music feature where the content is saveable and shareable.

**Comment by IzzySoft** [comment]
Ah, OK – added it to the "green list" then. Though just wondering: if your app saves the images, aren't they owned by it and could be accessed without special permission, in the context of "scoped storage"? Just asking – I wouldn't be the least surprised if that again is something dealt with in 100 different ways depending on Android version, vendor, ROM… SAF and permissions is kind of a "Pandora's box" :see_no_evil:

**Comment by 07jasjeet** [comment]
@IzzySoft depends on you :P

**Comment by IzzySoft** [comment]
OK, closing then. We can reopen anytime if needed. Thanks a lot!
