### ISSUE TITLE
APK available?

### ISSUE THREAD

**Issue by IzzySoft** [metabrainz/listenbrainz-android#86]
Did you consider including the APK with your [releases](https://github.com/metabrainz/listenbrainz-android/releases) here for the folks without access to Google's walled garden? Would be nice :smiley:

And btw, one thing that's not quite clear from the app description: where is the data aggregated that's used for recommendations? Is it collected to some server (if so, which one), or does it stay on-device until the user explicitly chooses to share with others?

Thanks in advance for your answers!

**Comment by 07jasjeet** [comment]
Hello! Thanks for taking our app into consideration. Please consider opening an issue at [LB Android Issue Board](https://tickets.metabrainz.org/secure/RapidBoard.jspa?rapidView=10&projectKey=MOBILE) and closing this one. This helps us keep track of all the issues at one place, hence solving problems faced by our users. PS Your suggestion is well received.

**Comment by IzzySoft** [comment]
Thanks for consideration! The idea was your app could maybe integrated with [my repo](https://apt.izzysoft.de/fdroid). As I'm having to run after thousands of projects, please understand I cannot go to too many different platforms, creating accounts etc.pp. – so I concentrate on those where apps are concentrated on (Codeberg, GitLab, Github). I hope it's OK for you if I stay here. Maybe you can take the issue "over there"? I fully accept if I have to wait a bit longer here.

PS: should results show your app would be eligible for [F-Droid.org](https://f-droid.org/) itself, I'll in turn gladly help you with "onboarding" there (disclosure: I'm one of the maintainers at F-Droid).

Thanks a lot!

**Comment by akshaaatt** [comment]
Hello @IzzySoft ! 
Thanks a lot for your interest in our app :)
I like the idea of adding the apk with the release on GitHub. https://github.com/kyze8439690/action-release-releaseapk looks promising for automating this stuff. I will update the README soon to answer the questions you asked. 

As for F-Droid, I am unsure if we will be allowed. We use the Spotify Android SDK and have plans to integrate Firebase for services like Cloud Messaging, which would exclude this app from F-Droid.

Thanks a lot for your concerns! :)

**Comment by IzzySoft** [comment]
Thanks for your reply, @akshaaatt ! Maybe I'm "just in time" then:

* Firebase: for Cloud Messaging, maybe rather look at [UnifiedPush](https://unifiedpush.org/)? That lets users decide which service to use. And for Play, you could have a flavor including their Firebase distributor (so the users there would not even notice the difference), while leaving it out with the foss flavor. As you write "like Cloud Messaging": for other parts of Firebase, there are replacements like [appwrite](https://github.com/appwrite/appwrite) and [Supabase](https://supabase.com/).
* For my repo, I'd *prefer* it as foss as it can be – but as you might know, my inclusion criteria are *a little* more lenient.

Looking forward to the APK then, and to the updated Readme :smiley:

**Comment by IzzySoft** [comment]
Just found you have the APK attached now, thanks! So ListenBrainz will [become available in my repo](https://apt.izzysoft.de/fdroid/index/apk/org.listenbrainz.android) with the next sync around 7 pm UTC. A question left: is Sentry configured opt-in or opt-out?

**Comment by akshaaatt** [comment]
Hi @IzzySoft thanks for your efforts. I have now updated the README to answer your questions. 
Sentry is yet to be configured to be opt-in or opt-out. We will take it up next month.

I don't think we will be using Firebase or any other such products in the near future as per the discussion with the team.

I have a question for you though, we use the Spotify Android SDK, doesn't that rule us out from F-Droid?

**Comment by IzzySoft** [comment]
> Hi @IzzySoft thanks for your efforts. I have now updated the README to answer your questions.

Thanks! Maybe you could add a link to [this place](https://apt.izzysoft.de/fdroid/index/apk/org.listenbrainz.android) in the "Downloads" section (and optionally also point to the releases of your own repo here)? If you wish, you can also [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for that (more than one, even one that would fit next to your download-counter-badge indicating which release/version is active in my repo :wink:).

Thanks for the clear words on data handling! So `NonFreeNet` will have to stay, and `NonFreeDep` as well (GMS, Spotify (see below)).

> Sentry is yet to be configured to be opt-in or opt-out. We will take it up next month.

So I leave the `Tracking` anti-feature up until you decided? If you make Sentry opt-in, that AF can be dropped.

> I don't think we will be using Firebase or any other such products in the near future as per the discussion with the team.

:+1: And as pointed out: should the need arise, you now know there are alternatives which are FOSS :smiley:

> I have a question for you though, we use the Spotify Android SDK, doesn't that rule us out from F-Droid?

A quick check: Yes, it will. The Spotify SDK is to be considered proprietary according to my library definitions. Why? Though it declares to be Apache-2 licensed in [their repo](https://github.com/spotify/android-sdk), the code cannot be found there – so we must assume that license only applies to the **samples** served in that repo, not to the SDK itself (the repo is somehow misnamed, it should be named `android-sdk-samples` or something like that). Should you have a different source please let me know and I'll take another look.

**Comment by IzzySoft** [comment]
PS: May I ask concerning two "unknown" libraries my scanner detected, what they might be, and where to find their source?

* `com.aemerse.share`
* `com.limurse.onboard`

Thanks in advance!

**Comment by akshaaatt** [comment]
Spotify iOS SDK which we use: https://github.com/spotify/ios-sdk

The 2 unknown libraries which you detected are both developed and managed by me, https://github.com/akshaaatt/Share-Android and https://github.com/akshaaatt/Onboarding-Android

**Comment by IzzySoft** [comment]
> Spotify iOS SDK which we use

Urn, iOS? I was talking about the Android app, sorry :wink: 

> The 2 unknown libraries which you detected are both developed and managed by me, [akshaaatt/Share-Android](https://github.com/akshaaatt/Share-Android) and [akshaaatt/Onboarding-Android](https://github.com/akshaaatt/Onboarding-Android)

Ah, cool, thanks! What license do they fall under? The "Share" one has none declared (the Onboarding one is clear).

**Comment by IzzySoft** [comment]
@akshaaatt would you please let me know the license for Share-Android, please? Or even better, include it with its repo? Thanks in advance!

**Comment by IzzySoft** [comment]
OK, added it to my library definitions without license for now (might cause apps using it to be flagged for missing licenses by those using the definitions, so as soon as you let me know I'll add the license to it).

**Comment by IzzySoft** [comment]
@akshaaatt you wrote in April:

> Sentry is yet to be configured to be opt-in or opt-out. We will take it up next month.

Now that May has passed: what's the status concerning this? I couldn't find a related commit, but maybe I just overlooked it.

**Comment by MaxEtMoritz** [comment]
@akshaaatt I'll just try to re-use this closed issue since it's kind of related:
The [GitHub action that should attach the APK to the GitHub release](https://github.com/metabrainz/listenbrainz-android/actions/runs/5326965880) somehow did not work for ListenBrainz 2.0.0.
It says it completed successfully, but the APK is not attached to the release.

Can someone have a look what has happened?

**Comment by akshaaatt** [comment]
My bad @MaxEtMoritz. I need to manually attach the apk to the release.
